In [8]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

#c처럼 3차원배열(2차원 배열이 연속적으로 여러 개 모인것)을 구현하는 것도 가능하다. 
c = np.array([
    [
        [0, 1, 2], 
        [3, 4, 5]
    ], 
    [
        [5, 4, 3], 
        [2, 1, 0]
    ]
    ])

print(c)




[1 2 3]
[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [9]:

#초기값이 0인배열,  1인배열을 생성가능
d = np.zeros(8)
print(d)

e = np.ones(8)
print(e)

#arrange()를 사용하면 range범위에 따른 배열 생성이 가능하다.
f = np.arange(8)
print(f)


[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [12]:
# 배열의 연산
import numpy as np

a = np.array([
    [0, 1, 2], 
    [3, 4, 5]
])

print(a)
print()
print(a + 3)
print()
print(a * 3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [15]:
import numpy as np

a = np.array([
    [0, 1, 2], 
    [3, 4, 5]
])

#:를 통해서 배열의 행과 열에 접근할 수 있다. 
print(a[1, :])
print()

print(a[:, 2])



[3 4 5]

[2 5]
[[ 1  3  5]
 [ 7  9 11]]


In [16]:
import numpy as np

a = np.array([
    [0, 1, 2], 
    [3, 4, 5]
])

def array_func(array):
    result = array * 2 + 1
    return result

b = array_func(a)

print(b)

[[ 1  3  5]
 [ 7  9 11]]
