행렬의 전치는 행과 열이 바뀌는 것을 의미한다. 

$$A=\begin{pmatrix}
1 & 1 & 3 \\
4 & 5 & 6
\end{pmatrix}
$$

\
$$A^T=
\begin{pmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{pmatrix}
$$

\
$$B=\begin{pmatrix}
a & b \\
c & d \\
e & f
\end{pmatrix}
$$

\
$$B^T=
\begin{pmatrix}
a & c & e\\
b & d & f \\
\end{pmatrix}
$$

In [2]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [3]:
행렬곱의 베이스는 앞행렬의 열수와 뒤 행렬의 행수가 일치해야한다는 것이었다. 
하지만 그렇지 않은 경우라도 전치에 의한 행렬곱을 할수있는 경우가 있다. 

즉 전치를 해서 바뀐 행렬의 값이 앞 행렬의 열수과 뒤행렬의 행 수와 일치한다면 
이를 통해 행렬 곱을 할 수 ㅣㅇㅆ는 것이다. 


SyntaxError: invalid syntax (<ipython-input-3-82defd6a6720>, line 1)

In [4]:
import numpy as mp

a = np.array([
    [0, 1, 2],
    [1, 2, 3]
])

b = np.array([
    [0, 1, 2],
    [1, 2, 3]
])

print(np.dot(a, b.T))

[[ 5  8]
 [ 8 14]]


In [5]:
import numpy as np

a = np.array([
    [0, 1, 2],
    [1, 2, 3]
])

b = np.array([
    [0, 1, 2],
    [2, 3, 4]
])

print(np.dot(a, b.T))

[[ 5 11]
 [ 8 20]]
