In [ ]:
# 행렬의곱

아래의 두 행렬이 있을때 행렬곱은 아래와 같다


$$A=\begin{pmatrix}
0 & 1 & 2 \\
1 & 2 & 3
\end{pmatrix}
$$

\
$$B=
\begin{pmatrix}
2 & 1 \\
2 & 1 \\
2 & 1
\end{pmatrix}
$$

\
$$
Answer = 
\begin{pmatrix}
(0 * 2) + (1 * 2) + (2 * 2) &  (0 * 1) + (1 * 1) + (2 * 1) \\
(1 * 2) + (2 * 2) + (3 * 2) & (1 * 1) + (2 * 1) + (3 * 1)
\end{pmatrix}
$$

\
\
\
행렬곱은 스칼라의 곱과 달리 앞 행렬과 뒤 행렬의 교환은 특정조건을 만족하 있는 경우를 제외할 수 없다. 
또한 행렬곱을 계산하려면 앞의 행렬의 열수와 뒤 행렬의 행수가 일치해야한다. 



In [5]:
# 이를 코드로 구현하면

import numpy as np

a = np.array([
            [0, 1, 2],
            [1, 2, 3]
            ])

b = np.array([
            [2, 1],
            [2, 1],
            [2, 1]
])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [ ]:
#  아다마르 곱

행렬의 요소별 곱은 아다마르곱이라고 한다.
행렬의 각 요소를 곱하면된다. 

$$ 
A=\begin{pmatrix}
    a_{11} & a_{12} & \cdots & a_{1n} \\
    a_{21} & a_{22} & \cdots & a_{2n} \\
   \vdots & \vdots & \ddots &  \vdots \\   
   a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}
 $$
 \
 $$
 B=\begin{pmatrix}
    b_{11} & b_{12} & \cdots & b_{1n} \\
    b_{21} & b_{22} & \cdots & b_{2n} \\
   \vdots & \vdots & \ddots &  \vdots \\   
   b_{m1} & b_{m2} & \cdots & b_{mn} 
\end{pmatrix}
$$
\
$$
A\circ B=\begin{pmatrix}
    a_{11}b_{11} & a_{12}b_{12} & \cdots &  a_{1n}b_{1n} \\
    a_{21}b_{21} & a_{22}b_{22} & \cdots & a_{2n}b_{2n} \\
   \vdots & \vdots & \ddots &  \vdots \\   
   a_{m1}b_{m1} & a_{m2}b_{m2} & \cdots & a_{mn}b_{mn} 
\end{pmatrix}
$$



In [7]:
#요소별 곱의 구현

import numpy as np

a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

b = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [8]:
# 연습문제

import numpy as np

a = np.array([
    [0, 1, 2],
    [1, 2, 3]
])

b = np.array([
    [0, 1],
    [1, 2],
    [2, 3]
])

# 행렬곱
print(np.dot(a, b))
print()

c = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

d = np.array([
    [0, 2, 0],
    [2, 0, 2],
    [0, 2, 0]
])

# 요소별 곱
print(c*d)


[[ 5  8]
 [ 8 14]]

[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
